### ISSUE TITLE
拜读请求

### ISSUE THREAD

**Issue by ly-ddd** [a839290771/SSVEP-BCI-OpenBCI#1]
老哥您好，看到您这边的GitHub仓库有修改，您这边是修改后再上传吗。小弟最近在学习open bci，这边能参考一下您这边写的代码吗？

**Comment by AI-Tianlong** [comment]
老哥您好，仓库今天刚开，东西还在整理ing，整理完后会及时上传哒。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "a839290771/SSVEP_OpenBCI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月13日(星期四) 晚上10:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[a839290771/SSVEP_OpenBCI] 拜读请求 (Issue #1)





 
老哥您好，看到您这边的GitHub仓库有修改，您这边是修改后再上传吗。小弟最近在学习open bci，这边能参考一下您这边写的代码吗？
