### ISSUE TITLE
关于Brainflow` 

### ISSUE THREAD

**Issue by dfqwer4321** [a839290771/SSVEP-BCI-OpenBCI#6]
请问能上传一下`Brainflow文件吗，不知道为什么在官网下载并添加路径以后没用，报错：错误使用 loadlibrary
生成 DataHandler_thunk_pcwin64 失败

**Comment by AI-Tianlong** [comment]
> 请问能上传一下`Brainflow文件吗，不知道为什么在官网下载并添加路径以后没用，报错：错误使用 loadlibrary
> 
> 生成 DataHandler_thunk_pcwin64 失败

您好，当时这个Brainflow在使用时需要在matlab中更改为C++编译器。
其实可以不用Brainflow这个库，使用这个库仅用了该库中的一个带阻滤波器作为陷波滤波器，您完全可以自己使用matlab自带函数完成带阻滤波器的设计，设计参数为：50Hz的中心频率，带阻宽度为2Hz，巴特沃斯滤波器，阶数为3，纹波0.2dB，您可以根据自己的情况进行陷波滤波器的设计（只要能把50Hz给滤掉就行），这里用Brainflow的DataFilter.bandstop()是自己偷了个懒🥺………之后我会上传Brainflow的文件的，并对该项目继续完善，希望这个回答对您有帮助，感谢🙏
