### ISSUE TITLE
请问BrainFlow 5.12.1的

### ISSUE THREAD

**Issue by cjmq** [a839290771/SSVEP-BCI-OpenBCI#8]
![image](https://github.com/AI-Tianlong/SSVEP-BCI-OpenBCI/assets/137464791/62d3fc01-1081-476b-9076-46a78ead4d31)
![image](https://github.com/AI-Tianlong/SSVEP-BCI-OpenBCI/assets/137464791/af372a2d-3886-488b-abe8-a420335ca783)
![image](https://github.com/AI-Tianlong/SSVEP-BCI-OpenBCI/assets/137464791/a3524fbd-5ec0-4bd1-9589-e8cba8e979da)
路径添加后还是报这个错误，能不能请教一下呢？感谢大佬

**Comment by Bu0717** [comment]
您好，这个问题是环境配置问题，我们当时也遇到了这个问题有些电脑可以配置成功。您可以看下我们手册提供的第二种方法。
![微信图片_20240304175844](https://github.com/AI-Tianlong/SSVEP-BCI-OpenBCI/assets/68641064/1f69a61c-4896-476e-bd0b-b81b8084b700)

![微信图片_20240304175831](https://github.com/AI-Tianlong/SSVEP-BCI-OpenBCI/assets/68641064/3623b6e7-6d9a-42c8-a2cd-640c0141402d)
